// <auto-generated />
using System;
using CSG.MI.TrMontrgSrv.EF;
using CSG.MI.TrMontrgSrv.Model.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CSG.MI.TrMontrgSrv.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210909033436_SProcedure")]
    partial class SProcedure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Npgsql:Tablespace", "mi_default")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.BoxEntity", b =>
                {
                    b.Property<string>("Ymd")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ymd");

                    b.Property<string>("Hms")
                        .HasColumnType("varchar(6)")
                        .HasColumnName("hms");

                    b.Property<int>("BoxId")
                        .HasColumnType("integer")
                        .HasColumnName("box_id");

                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("CaptureDt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("capture_dt");

                    b.Property<int>("Point1X")
                        .HasColumnType("integer")
                        .HasColumnName("p1_x");

                    b.Property<int>("Point1Y")
                        .HasColumnType("integer")
                        .HasColumnName("p1_y");

                    b.Property<int>("Point2X")
                        .HasColumnType("integer")
                        .HasColumnName("p2_x");

                    b.Property<int>("Point2Y")
                        .HasColumnType("integer")
                        .HasColumnName("p2_y");

                    b.Property<float>("T90th")
                        .HasColumnType("real")
                        .HasColumnName("t_90th");

                    b.Property<float>("Tavg")
                        .HasColumnType("real")
                        .HasColumnName("t_avg");

                    b.Property<float>("Tdiff")
                        .HasColumnType("real")
                        .HasColumnName("t_diff");

                    b.Property<float>("Tmax")
                        .HasColumnType("real")
                        .HasColumnName("t_max");

                    b.Property<int>("TmaxX")
                        .HasColumnType("integer")
                        .HasColumnName("t_max_x");

                    b.Property<int>("TmaxY")
                        .HasColumnType("integer")
                        .HasColumnName("t_max_y");

                    b.Property<float>("Tmin")
                        .HasColumnType("real")
                        .HasColumnName("t_min");

                    b.Property<DateTime?>("UpdatedDt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("upd_dt")
                        .HasDefaultValueSql("current_timestamp");

                    b.HasKey("Ymd", "Hms", "BoxId", "DeviceId")
                        .HasName("box_pkey");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("box_device_id_idx");

                    b.HasIndex(new[] { "DeviceId" }, "box_device_id_idx");

                    b.ToTable("box", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.CfgEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CaptureDt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("capture_dt");

                    b.Property<ConfigJson>("CfgJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cfg_file");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id");

                    b.Property<string>("Hms")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasColumnName("hms");

                    b.Property<DateTime?>("UpdatedDt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("upd_dt")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("Ymd")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ymd");

                    b.HasKey("Id")
                        .HasName("cfg_pkey");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("cfg_device_id_idx");

                    b.HasIndex("Ymd", "Hms")
                        .HasDatabaseName("cfg_ymd_hms_idx");

                    b.HasIndex(new[] { "DeviceId" }, "cfg_device_id_idx");

                    b.HasIndex(new[] { "Ymd", "Hms" }, "cfg_ymd_hms_idx");

                    b.HasIndex(new[] { "Ymd", "Hms" }, "ix_ymd_hms");

                    b.ToTable("cfg", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("desn");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("loc_id");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.Property<int?>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("ord");

                    b.Property<string>("PlantId")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("plant_id");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("root_path");

                    b.Property<DateTime?>("UpdatedDt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("upd_dt")
                        .HasDefaultValueSql("current_timestamp");

                    b.HasKey("DeviceId")
                        .HasName("device_pkey");

                    b.HasIndex("LocationId", "PlantId")
                        .HasDatabaseName("device_loc_id_plant_id_idx");

                    b.HasIndex(new[] { "LocationId", "PlantId" }, "device_loc_id_plant_id_idx");

                    b.ToTable("device", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.FrameEntity", b =>
                {
                    b.Property<string>("Ymd")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ymd");

                    b.Property<string>("Hms")
                        .HasColumnType("varchar(6)")
                        .HasColumnName("hms");

                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("CaptureDt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("capture_dt");

                    b.Property<float>("T90th")
                        .HasColumnType("real")
                        .HasColumnName("t_90th");

                    b.Property<float>("Tavg")
                        .HasColumnType("real")
                        .HasColumnName("t_avg");

                    b.Property<float>("Tdiff")
                        .HasColumnType("real")
                        .HasColumnName("t_diff");

                    b.Property<float>("Tmax")
                        .HasColumnType("real")
                        .HasColumnName("t_max");

                    b.Property<int>("TmaxX")
                        .HasColumnType("integer")
                        .HasColumnName("t_max_x");

                    b.Property<int>("TmaxY")
                        .HasColumnType("integer")
                        .HasColumnName("t_max_y");

                    b.Property<float>("Tmin")
                        .HasColumnType("real")
                        .HasColumnName("t_min");

                    b.Property<DateTime?>("UpdatedDt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("upd_dt")
                        .HasDefaultValueSql("current_timestamp");

                    b.HasKey("Ymd", "Hms", "DeviceId")
                        .HasName("frame_pkey");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("frame_device_id_idx");

                    b.HasIndex(new[] { "DeviceId" }, "frame_device_id_idx");

                    b.ToTable("frame", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.MediumEntity", b =>
                {
                    b.Property<string>("Ymd")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ymd");

                    b.Property<string>("Hms")
                        .HasColumnType("varchar(6)")
                        .HasColumnName("hms");

                    b.Property<string>("MediumType")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("medium_type");

                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("CaptureDt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("capture_dt");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("file_content");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("file_type");

                    b.Property<DateTime?>("UpdatedDt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("upd_dt")
                        .HasDefaultValueSql("current_timestamp");

                    b.HasKey("Ymd", "Hms", "MediumType", "DeviceId")
                        .HasName("medium_pkey");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("medium_device_id_idx");

                    b.HasIndex(new[] { "DeviceId" }, "medium_device_id_idx");

                    b.ToTable("medium", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.RoiEntity", b =>
                {
                    b.Property<string>("Ymd")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ymd");

                    b.Property<string>("Hms")
                        .HasColumnType("varchar(6)")
                        .HasColumnName("hms");

                    b.Property<int>("RoiId")
                        .HasColumnType("integer")
                        .HasColumnName("roi_id");

                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("CaptureDt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("capture_dt");

                    b.Property<int>("Point1X")
                        .HasColumnType("integer")
                        .HasColumnName("p1_x");

                    b.Property<int>("Point1Y")
                        .HasColumnType("integer")
                        .HasColumnName("p1_y");

                    b.Property<int>("Point2X")
                        .HasColumnType("integer")
                        .HasColumnName("p2_x");

                    b.Property<int>("Point2Y")
                        .HasColumnType("integer")
                        .HasColumnName("p2_y");

                    b.Property<float>("T90th")
                        .HasColumnType("real")
                        .HasColumnName("t_90th");

                    b.Property<float>("Tavg")
                        .HasColumnType("real")
                        .HasColumnName("t_avg");

                    b.Property<float>("Tdiff")
                        .HasColumnType("real")
                        .HasColumnName("t_diff");

                    b.Property<float>("Tmax")
                        .HasColumnType("real")
                        .HasColumnName("t_max");

                    b.Property<int>("TmaxX")
                        .HasColumnType("integer")
                        .HasColumnName("t_max_x");

                    b.Property<int>("TmaxY")
                        .HasColumnType("integer")
                        .HasColumnName("t_max_y");

                    b.Property<float>("Tmin")
                        .HasColumnType("real")
                        .HasColumnName("t_min");

                    b.Property<DateTime?>("UpdatedDt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("upd_dt")
                        .HasDefaultValueSql("current_timestamp");

                    b.HasKey("Ymd", "Hms", "RoiId", "DeviceId")
                        .HasName("roi_pkey");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("roi_device_id_idx");

                    b.HasIndex(new[] { "DeviceId" }, "roi_device_id_idx");

                    b.ToTable("roi", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.BoxEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", "Device")
                        .WithMany("Boxes")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("box_device_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.CfgEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", "Device")
                        .WithMany("Cfgs")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("cfg_device_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.FrameEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", "Device")
                        .WithMany("Frames")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("frame_device_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.MediumEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", "Device")
                        .WithMany("Media")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("medium_device_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.RoiEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", "Device")
                        .WithMany("Rois")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("roi_device_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", b =>
                {
                    b.Navigation("Boxes");

                    b.Navigation("Cfgs");

                    b.Navigation("Frames");

                    b.Navigation("Media");

                    b.Navigation("Rois");
                });
#pragma warning restore 612, 618
        }
    }
}
