// <auto-generated />
using System;
using CSG.MI.TrMontrgSrv.EF;
using CSG.MI.TrMontrgSrv.Model.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CSG.MI.TrMontrgSrv.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Npgsql:Tablespace", "mi_default")
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.BoxCtrlEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id")
                        .HasComment("Device ID");

                    b.Property<int?>("InspRadiusPixel")
                        .HasColumnType("integer")
                        .HasColumnName("insp_r_px")
                        .HasComment("Inspection radius in pixel");

                    b.Property<float?>("TMax")
                        .HasColumnType("real")
                        .HasColumnName("t_max")
                        .HasComment("Max. temperature");

                    b.Property<float?>("TWarning")
                        .HasColumnType("real")
                        .HasColumnName("t_warning")
                        .HasComment("Warning temp.");

                    b.HasKey("DeviceId")
                        .HasName("box_ctrl_pkey");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("box_ctrl_device_id_idx");

                    b.HasIndex(new[] { "DeviceId" }, "box_ctrl_device_id_idx");

                    b.ToTable("box_ctrl", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.BoxEntity", b =>
                {
                    b.Property<string>("Ymd")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ymd")
                        .HasComment("Data captured date");

                    b.Property<string>("Hms")
                        .HasColumnType("varchar(6)")
                        .HasColumnName("hms")
                        .HasComment("Data captured time");

                    b.Property<int>("BoxId")
                        .HasColumnType("integer")
                        .HasColumnName("box_id")
                        .HasComment("Box ID");

                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id")
                        .HasComment("Device ID");

                    b.Property<DateTime?>("CaptureDt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("capture_dt")
                        .HasComment("Data captured date time");

                    b.Property<int>("Point1X")
                        .HasColumnType("integer")
                        .HasColumnName("p1_x")
                        .HasComment("X-coordinate value of top-left point");

                    b.Property<int>("Point1Y")
                        .HasColumnType("integer")
                        .HasColumnName("p1_y")
                        .HasComment("Y-coordinate value of top-left point");

                    b.Property<int>("Point2X")
                        .HasColumnType("integer")
                        .HasColumnName("p2_x")
                        .HasComment("X-coordinate value of bottom-right point");

                    b.Property<int>("Point2Y")
                        .HasColumnType("integer")
                        .HasColumnName("p2_y")
                        .HasComment("Y-coordinate value of bottom-right point");

                    b.Property<float>("T90th")
                        .HasColumnType("real")
                        .HasColumnName("t_90th")
                        .HasComment("90 percentile temperature");

                    b.Property<float>("TAvg")
                        .HasColumnType("real")
                        .HasColumnName("t_avg")
                        .HasComment("Average temperature");

                    b.Property<float>("TDiff")
                        .HasColumnType("real")
                        .HasColumnName("t_diff")
                        .HasComment("Max. - min temperature");

                    b.Property<float>("TMax")
                        .HasColumnType("real")
                        .HasColumnName("t_max")
                        .HasComment("Max. temperature");

                    b.Property<int>("TMaxX")
                        .HasColumnType("integer")
                        .HasColumnName("t_max_x")
                        .HasComment("X-coordinate value of max. temperature");

                    b.Property<int>("TMaxY")
                        .HasColumnType("integer")
                        .HasColumnName("t_max_y")
                        .HasComment("Y-coordinate value of min. temperature");

                    b.Property<float>("TMin")
                        .HasColumnType("real")
                        .HasColumnName("t_min")
                        .HasComment("Min. temperature");

                    b.Property<DateTime?>("UpdatedDt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("upd_dt")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("Last updated");

                    b.HasKey("Ymd", "Hms", "BoxId", "DeviceId")
                        .HasName("box_pkey");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("box_device_id_idx");

                    b.HasIndex(new[] { "DeviceId" }, "box_device_id_idx");

                    b.ToTable("box", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.CfgEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Unique ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CaptureDt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("capture_dt")
                        .HasComment("Data captured date time");

                    b.Property<ConfigJson>("CfgJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cfg_file")
                        .HasComment("Configuration json file");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id")
                        .HasComment("Device ID");

                    b.Property<string>("Hms")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasColumnName("hms")
                        .HasComment("Data captured time");

                    b.Property<DateTime?>("UpdatedDt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("upd_dt")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("Last updated");

                    b.Property<string>("Ymd")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ymd")
                        .HasComment("Data captured date");

                    b.HasKey("Id")
                        .HasName("cfg_pkey");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("cfg_device_id_idx");

                    b.HasIndex("Ymd", "Hms")
                        .HasDatabaseName("cfg_ymd_hms_idx");

                    b.HasIndex(new[] { "DeviceId" }, "cfg_device_id_idx");

                    b.HasIndex(new[] { "Ymd", "Hms" }, "cfg_ymd_hms_idx");

                    b.HasIndex(new[] { "Ymd", "Hms" }, "ix_ymd_hms");

                    b.ToTable("cfg", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.Dashboard.CurBoxEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id")
                        .HasComment("Device ID");

                    b.Property<int?>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<float?>("TAvg")
                        .HasColumnType("real")
                        .HasColumnName("t_avg")
                        .HasComment("Average temperature");

                    b.Property<float?>("TDiff")
                        .HasColumnType("real")
                        .HasColumnName("t_diff")
                        .HasComment("Max - Min temperature");

                    b.Property<float?>("TMax")
                        .HasColumnType("real")
                        .HasColumnName("t_max")
                        .HasComment("Max temperature");

                    b.Property<float?>("TMin")
                        .HasColumnType("real")
                        .HasColumnName("t_min")
                        .HasComment("Min temperature");

                    b.HasKey("DeviceId", "Id")
                        .HasName("dim_cur_box_pk");

                    b.ToTable("dim_cur_box", "dashboard");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.Dashboard.CurDeviceEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id")
                        .HasComment("Device ID");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("desn")
                        .HasComment("Description");

                    b.Property<string>("LocationId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("loc_id")
                        .HasComment("Location ID");

                    b.Property<string>("PlantId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("plant_id")
                        .HasComment("Plant ID");

                    b.HasKey("DeviceId")
                        .HasName("fact_device_pk");

                    b.ToTable("fact_device", "dashboard");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.Dashboard.CurFrameEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id")
                        .HasComment("Device ID");

                    b.Property<int?>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<float?>("TAvg")
                        .HasColumnType("real")
                        .HasColumnName("t_avg")
                        .HasComment("Average temperature");

                    b.Property<float?>("TDiff")
                        .HasColumnType("real")
                        .HasColumnName("t_diff")
                        .HasComment("Max - Min temperature");

                    b.Property<float?>("TMax")
                        .HasColumnType("real")
                        .HasColumnName("t_max")
                        .HasComment("Max temperature");

                    b.Property<float?>("TMin")
                        .HasColumnType("real")
                        .HasColumnName("t_min")
                        .HasComment("Min temperature");

                    b.HasKey("DeviceId", "Id")
                        .HasName("dim_cur_frame_pk");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("dim_cur_frame", "dashboard");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.Dashboard.CurRoiEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id")
                        .HasComment("Device ID");

                    b.Property<int?>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<float?>("TAvg")
                        .HasColumnType("real")
                        .HasColumnName("t_avg")
                        .HasComment("Average temperature");

                    b.Property<float?>("TDiff")
                        .HasColumnType("real")
                        .HasColumnName("t_diff")
                        .HasComment("Max - Min temperature");

                    b.Property<float?>("TMax")
                        .HasColumnType("real")
                        .HasColumnName("t_max")
                        .HasComment("Max temperature");

                    b.Property<float?>("TMin")
                        .HasColumnType("real")
                        .HasColumnName("t_min")
                        .HasComment("Min temperature");

                    b.HasKey("DeviceId", "Id")
                        .HasName("dim_cur_roi_pk");

                    b.ToTable("dim_cur_roi", "dashboard");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.DeviceCtrlEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id")
                        .HasComment("Device ID");

                    b.Property<float>("LevelATo")
                        .HasColumnType("real")
                        .HasColumnName("lvl_a_to")
                        .HasComment("Upper limit of level A");

                    b.Property<float>("LevelBTo")
                        .HasColumnType("real")
                        .HasColumnName("lvl_b_to")
                        .HasComment("Upper limit of level B");

                    b.Property<float>("LevelCTo")
                        .HasColumnType("real")
                        .HasColumnName("lvl_c_to")
                        .HasComment("Upper limit of level C");

                    b.Property<int>("MonitoringHour")
                        .HasColumnType("integer")
                        .HasColumnName("montrg_hr")
                        .HasComment("Monitoring hour (up to now)");

                    b.Property<string>("NelsonRule")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nelson_rule")
                        .HasComment("Nelson rules to apply");

                    b.HasKey("DeviceId")
                        .HasName("device_ctrl_pkey");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("device_ctrl_device_id_idx");

                    b.HasIndex(new[] { "DeviceId" }, "device_ctrl_device_id_idx");

                    b.ToTable("device_ctrl", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id")
                        .HasComment("Device ID");

                    b.Property<int?>("ApiPort")
                        .HasColumnType("integer")
                        .HasColumnName("api_port")
                        .HasComment("Port number of RESTful API service");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("desn")
                        .HasComment("Description");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_addr")
                        .HasComment("IP address");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("loc_id")
                        .HasComment("Location ID");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name")
                        .HasComment("Name of device");

                    b.Property<int?>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("ord")
                        .HasComment("Order by");

                    b.Property<string>("PlantId")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("plant_id")
                        .HasComment("Plant ID");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("root_path")
                        .HasComment("Root path of data directory");

                    b.Property<int?>("UiPort")
                        .HasColumnType("integer")
                        .HasColumnName("ui_port")
                        .HasComment("Port number of Web UI service");

                    b.Property<DateTime?>("UpdatedDt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("upd_dt")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("Last updated");

                    b.HasKey("DeviceId")
                        .HasName("device_pkey");

                    b.HasIndex("LocationId", "PlantId")
                        .HasDatabaseName("device_loc_id_plant_id_idx");

                    b.HasIndex(new[] { "LocationId", "PlantId" }, "device_loc_id_plant_id_idx");

                    b.ToTable("device", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.EvntLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Unique ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_id")
                        .HasComment("Area ID");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id")
                        .HasComment("Device ID");

                    b.Property<string>("DiffLevel")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("diff_lvl")
                        .HasComment("Level of diff. temp");

                    b.Property<DateTime?>("EmailedDt")
                        .HasColumnType("timestamp")
                        .HasColumnName("emailed_dt")
                        .HasComment("Emailed date time");

                    b.Property<DateTime>("EvntDt")
                        .HasColumnType("timestamp")
                        .HasColumnName("evnt_dt")
                        .HasComment("Event date time");

                    b.Property<string>("EvntLevel")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("evnt_lvl")
                        .HasComment("Level of event");

                    b.Property<string>("EvntType")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("evnt_type")
                        .HasComment("Type of event");

                    b.Property<string>("Hms")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasColumnName("hms")
                        .HasComment("Event time");

                    b.Property<string>("InspArea")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("insp_area")
                        .HasComment("Inspection Area");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("loc_id")
                        .HasComment("Location ID");

                    b.Property<float?>("MeaValue")
                        .HasColumnType("real")
                        .HasColumnName("mea_value")
                        .HasComment("Measured(actual) value");

                    b.Property<string>("Message")
                        .HasColumnType("varchar")
                        .HasColumnName("msg")
                        .HasComment("Event message");

                    b.Property<string>("PlantId")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("plant_id")
                        .HasComment("Plant ID");

                    b.Property<float?>("SetValue")
                        .HasColumnType("real")
                        .HasColumnName("set_value")
                        .HasComment("Setting value");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title")
                        .HasComment("Title of event");

                    b.Property<DateTime?>("UpdatedDt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("upd_dt")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("Last updated");

                    b.Property<string>("Ymd")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ymd")
                        .HasComment("Event date");

                    b.HasKey("Id")
                        .HasName("evnt_log_pkey");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("evnt_log_device_id_idx");

                    b.HasIndex("EvntDt")
                        .HasDatabaseName("evnt_log_evnt_dt_idx");

                    b.HasIndex("Ymd", "Hms")
                        .HasDatabaseName("evnt_log_ymd_hms_idx");

                    b.HasIndex(new[] { "DeviceId" }, "evnt_log_device_id_idx");

                    b.HasIndex(new[] { "Ymd", "Hms" }, "evnt_log_ymd_hms_idx");

                    b.HasIndex(new[] { "Ymd", "Hms" }, "ix_ymd_hms")
                        .HasDatabaseName("ix_ymd_hms1");

                    b.ToTable("evnt_log", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.FrameCtrlEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id")
                        .HasComment("Device ID");

                    b.Property<float?>("LclIDiff")
                        .HasColumnType("real")
                        .HasColumnName("lcl_i_diff")
                        .HasComment("LCL of I-chart(diff temp. base)");

                    b.Property<float?>("LclIMax")
                        .HasColumnType("real")
                        .HasColumnName("lcl_i_max")
                        .HasComment("LCL of I-chart(max temp. base)");

                    b.Property<float?>("TWarning")
                        .HasColumnType("real")
                        .HasColumnName("t_warning")
                        .HasComment("Warning temp.");

                    b.Property<float?>("UclIDiff")
                        .HasColumnType("real")
                        .HasColumnName("ucl_i_diff")
                        .HasComment("UCL of I-chart(diff temp. base)	");

                    b.Property<float?>("UclIMax")
                        .HasColumnType("real")
                        .HasColumnName("ucl_i_max")
                        .HasComment("UCL of I-chart(max temp. base)");

                    b.Property<float?>("UclMrDiff")
                        .HasColumnType("real")
                        .HasColumnName("ucl_mr_diff")
                        .HasComment("UCL of MR-chart(diff temp. base)");

                    b.Property<float?>("UclMrMax")
                        .HasColumnType("real")
                        .HasColumnName("ucl_mr_max")
                        .HasComment("UCL of MR-chart(max temp. base)");

                    b.HasKey("DeviceId")
                        .HasName("frame_ctrl_pkey");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("frame_ctrl_device_id_idx");

                    b.HasIndex(new[] { "DeviceId" }, "frame_ctrl_device_id_idx");

                    b.ToTable("frame_ctrl", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.FrameEntity", b =>
                {
                    b.Property<string>("Ymd")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ymd")
                        .HasComment("Data captured date");

                    b.Property<string>("Hms")
                        .HasColumnType("varchar(6)")
                        .HasColumnName("hms")
                        .HasComment("Data captured time");

                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id")
                        .HasComment("Device ID");

                    b.Property<DateTime?>("CaptureDt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("capture_dt")
                        .HasComment("Data captured date time");

                    b.Property<float>("T90th")
                        .HasColumnType("real")
                        .HasColumnName("t_90th")
                        .HasComment("90 percentile temperature");

                    b.Property<float>("TAvg")
                        .HasColumnType("real")
                        .HasColumnName("t_avg")
                        .HasComment("Average temperature");

                    b.Property<float>("TDiff")
                        .HasColumnType("real")
                        .HasColumnName("t_diff")
                        .HasComment("Max. - min temperature");

                    b.Property<float>("TMax")
                        .HasColumnType("real")
                        .HasColumnName("t_max")
                        .HasComment("Max. temperature");

                    b.Property<int>("TMaxX")
                        .HasColumnType("integer")
                        .HasColumnName("t_max_x")
                        .HasComment("X-coordinate value of max. temperature");

                    b.Property<int>("TMaxY")
                        .HasColumnType("integer")
                        .HasColumnName("t_max_y")
                        .HasComment("Y-coordinate value of min. temperature");

                    b.Property<float>("TMin")
                        .HasColumnType("real")
                        .HasColumnName("t_min")
                        .HasComment("Min. temperature");

                    b.Property<int?>("TMinX")
                        .HasColumnType("integer")
                        .HasColumnName("t_min_x")
                        .HasComment("X-coordinate value of min. temperature");

                    b.Property<int?>("TMinY")
                        .HasColumnType("integer")
                        .HasColumnName("t_min_y")
                        .HasComment("Y-coordinate value of min. temperature");

                    b.Property<DateTime?>("UpdatedDt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("upd_dt")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("Last updated");

                    b.HasKey("Ymd", "Hms", "DeviceId")
                        .HasName("frame_pkey");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("frame_device_id_idx");

                    b.HasIndex("DeviceId", "CaptureDt")
                        .HasDatabaseName("frame_device_id_capture_dt_idx");

                    b.HasIndex(new[] { "DeviceId" }, "frame_device_id_idx");

                    b.ToTable("frame", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.GrpKeyEntity", b =>
                {
                    b.Property<string>("Group")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("grp")
                        .HasComment("Group name");

                    b.Property<string>("Key")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("key")
                        .HasComment("Key value");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("desn")
                        .HasComment("Description");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean")
                        .HasColumnName("inactive")
                        .HasComment("Inactive status");

                    b.Property<int?>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("ord")
                        .HasComment("Order by");

                    b.HasKey("Group", "Key")
                        .HasName("grp_key_pkey");

                    b.ToTable("grp_key", "public");

                    b.HasData(
                        new
                        {
                            Group = "plant_id",
                            Key = "HQ",
                            Inactive = false
                        },
                        new
                        {
                            Group = "plant_id",
                            Key = "VJ",
                            Inactive = false
                        },
                        new
                        {
                            Group = "plant_id",
                            Key = "JJ",
                            Inactive = false
                        },
                        new
                        {
                            Group = "plant_id",
                            Key = "CKP",
                            Inactive = false
                        },
                        new
                        {
                            Group = "plant_id",
                            Key = "JJS",
                            Inactive = false
                        },
                        new
                        {
                            Group = "plant_id",
                            Key = "RJ",
                            Inactive = false
                        },
                        new
                        {
                            Group = "plant_id",
                            Key = "QD",
                            Inactive = false
                        },
                        new
                        {
                            Group = "medium_type",
                            Key = "ir",
                            Description = "IR camera image",
                            Inactive = false
                        },
                        new
                        {
                            Group = "medium_type",
                            Key = "rgb",
                            Description = "RGB camera image",
                            Inactive = false
                        },
                        new
                        {
                            Group = "medium_type",
                            Key = "cfg",
                            Description = "Confiruation file",
                            Inactive = false
                        },
                        new
                        {
                            Group = "medium_type",
                            Key = "temp",
                            Description = "Temperature summary json",
                            Inactive = false
                        },
                        new
                        {
                            Group = "medium_type",
                            Key = "raw",
                            Description = "Temperature raw csv",
                            Inactive = false
                        },
                        new
                        {
                            Group = "file_type",
                            Key = "json",
                            Inactive = false
                        },
                        new
                        {
                            Group = "file_type",
                            Key = "csv",
                            Inactive = false
                        },
                        new
                        {
                            Group = "file_type",
                            Key = "jpg",
                            Inactive = false
                        },
                        new
                        {
                            Group = "event_type",
                            Key = "MaxTemp",
                            Description = "Max. temperature",
                            Inactive = false
                        },
                        new
                        {
                            Group = "event_type",
                            Key = "DiffLevel",
                            Description = "Diff. level",
                            Inactive = false
                        },
                        new
                        {
                            Group = "event_type",
                            Key = "UCL",
                            Description = "Upper control limit",
                            Inactive = false
                        },
                        new
                        {
                            Group = "event_type",
                            Key = "LCL",
                            Description = "Lower control limit",
                            Inactive = false
                        },
                        new
                        {
                            Group = "event_type",
                            Key = "NelsonRule",
                            Description = "Nelson rule",
                            Inactive = false
                        },
                        new
                        {
                            Group = "event_lvl",
                            Key = "Urgent",
                            Inactive = false
                        },
                        new
                        {
                            Group = "event_lvl",
                            Key = "Warning",
                            Inactive = false
                        },
                        new
                        {
                            Group = "event_lvl",
                            Key = "Info",
                            Inactive = false
                        },
                        new
                        {
                            Group = "event_lvl",
                            Key = "Error",
                            Inactive = false
                        });
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.MailingAddrEntity", b =>
                {
                    b.Property<string>("PlantId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("plant_id")
                        .HasComment("Plant ID");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email")
                        .HasComment("Email");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean")
                        .HasColumnName("inactive")
                        .HasComment("Inactive status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name")
                        .HasComment("Full name");

                    b.Property<string>("Team")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("team")
                        .HasComment("Team name");

                    b.Property<string>("Telephone")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("tel")
                        .HasComment("Telephone number");

                    b.HasKey("PlantId", "Email")
                        .HasName("mailing_addr_pkey");

                    b.ToTable("mailing_addr", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.MediumEntity", b =>
                {
                    b.Property<string>("Ymd")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ymd")
                        .HasComment("Data captured date");

                    b.Property<string>("Hms")
                        .HasColumnType("varchar(6)")
                        .HasColumnName("hms")
                        .HasComment("Data captured time");

                    b.Property<string>("MediumType")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("medium_type")
                        .HasComment("Medium type");

                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id")
                        .HasComment("Device ID");

                    b.Property<DateTime?>("CaptureDt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("capture_dt")
                        .HasComment("Data captured date time");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("file_content")
                        .HasComment("File content");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name")
                        .HasComment("File name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size")
                        .HasComment("File size in bytes");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("file_type")
                        .HasComment("File type");

                    b.Property<DateTime?>("UpdatedDt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("upd_dt")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("Last updated");

                    b.HasKey("Ymd", "Hms", "MediumType", "DeviceId")
                        .HasName("medium_pkey");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("medium_device_id_idx");

                    b.HasIndex(new[] { "DeviceId" }, "medium_device_id_idx");

                    b.ToTable("medium", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.RoiCtrlEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id")
                        .HasComment("Device ID");

                    b.Property<int>("RoiId")
                        .HasColumnType("integer")
                        .HasColumnName("roi_id")
                        .HasComment("ROI ID");

                    b.Property<float?>("LclIDiff")
                        .HasColumnType("real")
                        .HasColumnName("lcl_i_diff")
                        .HasComment("LCL of I-chart(diff temp. base)");

                    b.Property<float?>("LclIMax")
                        .HasColumnType("real")
                        .HasColumnName("lcl_i_max")
                        .HasComment("LCL of I-chart(max temp. base)");

                    b.Property<float?>("TWarning")
                        .HasColumnType("real")
                        .HasColumnName("t_warning")
                        .HasComment("Warning temp.");

                    b.Property<float?>("UclIDiff")
                        .HasColumnType("real")
                        .HasColumnName("ucl_i_diff")
                        .HasComment("UCL of I-chart(diff temp. base)");

                    b.Property<float?>("UclIMax")
                        .HasColumnType("real")
                        .HasColumnName("ucl_i_max")
                        .HasComment("UCL of I-chart(max temp. base)");

                    b.Property<float?>("UclMrDiff")
                        .HasColumnType("real")
                        .HasColumnName("ucl_mr_diff")
                        .HasComment("UCL of MR-chart(diff temp. base)");

                    b.Property<float?>("UclMrMax")
                        .HasColumnType("real")
                        .HasColumnName("ucl_mr_max")
                        .HasComment("UCL of MR-chart(max temp. base)");

                    b.HasKey("DeviceId", "RoiId")
                        .HasName("roi_ctrl_pkey");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("roi_ctrl_device_id_idx");

                    b.HasIndex(new[] { "DeviceId" }, "roi_ctrl_device_id_idx");

                    b.ToTable("roi_ctrl", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.RoiEntity", b =>
                {
                    b.Property<string>("Ymd")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ymd")
                        .HasComment("Data captured date");

                    b.Property<string>("Hms")
                        .HasColumnType("varchar(6)")
                        .HasColumnName("hms")
                        .HasComment("Data captured time");

                    b.Property<int>("RoiId")
                        .HasColumnType("integer")
                        .HasColumnName("roi_id")
                        .HasComment("ROI ID");

                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id")
                        .HasComment("Device ID");

                    b.Property<DateTime?>("CaptureDt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("capture_dt")
                        .HasComment("Data captured date time");

                    b.Property<int>("Point1X")
                        .HasColumnType("integer")
                        .HasColumnName("p1_x")
                        .HasComment("X-coordinate value of top-left point");

                    b.Property<int>("Point1Y")
                        .HasColumnType("integer")
                        .HasColumnName("p1_y")
                        .HasComment("Y-coordinate value of top-left point");

                    b.Property<int>("Point2X")
                        .HasColumnType("integer")
                        .HasColumnName("p2_x")
                        .HasComment("X-coordinate value of bottom-right point");

                    b.Property<int>("Point2Y")
                        .HasColumnType("integer")
                        .HasColumnName("p2_y")
                        .HasComment("Y-coordinate value of bottom-right point");

                    b.Property<float>("T90th")
                        .HasColumnType("real")
                        .HasColumnName("t_90th")
                        .HasComment("90 percentile temperature");

                    b.Property<float>("TAvg")
                        .HasColumnType("real")
                        .HasColumnName("t_avg")
                        .HasComment("Average temperature");

                    b.Property<float>("TDiff")
                        .HasColumnType("real")
                        .HasColumnName("t_diff")
                        .HasComment("Max. - min temperature");

                    b.Property<float>("TMax")
                        .HasColumnType("real")
                        .HasColumnName("t_max")
                        .HasComment("Max. temperature");

                    b.Property<int>("TMaxX")
                        .HasColumnType("integer")
                        .HasColumnName("t_max_x")
                        .HasComment("X-coordinate value of max. temperature");

                    b.Property<int>("TMaxY")
                        .HasColumnType("integer")
                        .HasColumnName("t_max_y")
                        .HasComment("Y-coordinate value of min. temperature");

                    b.Property<float>("TMin")
                        .HasColumnType("real")
                        .HasColumnName("t_min")
                        .HasComment("Min. temperature");

                    b.Property<DateTime?>("UpdatedDt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("upd_dt")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("Last updated");

                    b.HasKey("Ymd", "Hms", "RoiId", "DeviceId")
                        .HasName("roi_pkey");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("roi_device_id_idx");

                    b.HasIndex("DeviceId", "RoiId", "CaptureDt")
                        .HasDatabaseName("roi_device_id_roi_id_capture_dt_idx");

                    b.HasIndex(new[] { "DeviceId" }, "roi_device_id_idx");

                    b.ToTable("roi", "public");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.BoxCtrlEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", "Device")
                        .WithOne("BoxCtrl")
                        .HasForeignKey("CSG.MI.TrMontrgSrv.EF.Entities.BoxCtrlEntity", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("box_ctrl_device_id_fkey");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.BoxEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", "Device")
                        .WithMany("Boxes")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("box_device_id_fkey");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.CfgEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", "Device")
                        .WithMany("Cfgs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("cfg_device_id_fkey");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.Dashboard.CurBoxEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.Dashboard.CurDeviceEntity", "CurDevice")
                        .WithMany("Boxes")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurDevice");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.Dashboard.CurFrameEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.Dashboard.CurDeviceEntity", "CurDevice")
                        .WithOne("Frame")
                        .HasForeignKey("CSG.MI.TrMontrgSrv.EF.Entities.Dashboard.CurFrameEntity", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurDevice");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.Dashboard.CurRoiEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.Dashboard.CurDeviceEntity", "CurDevice")
                        .WithMany("Roies")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurDevice");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.DeviceCtrlEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", "Device")
                        .WithOne("DeviceCtrl")
                        .HasForeignKey("CSG.MI.TrMontrgSrv.EF.Entities.DeviceCtrlEntity", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("device_ctrl_device_id_fkey");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.EvntLogEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", "Device")
                        .WithMany("EvntLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("evnt_log_device_id_fkey");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.FrameCtrlEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", "Device")
                        .WithOne("FrameCtrl")
                        .HasForeignKey("CSG.MI.TrMontrgSrv.EF.Entities.FrameCtrlEntity", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("frame_ctrl_device_id_fkey");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.FrameEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", "Device")
                        .WithMany("Frames")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("frame_device_id_fkey");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.MediumEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", "Device")
                        .WithMany("Media")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("medium_device_id_fkey");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.RoiCtrlEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", "Device")
                        .WithMany("RoiCtrls")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("roi_ctrl_device_id_fkey");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.RoiEntity", b =>
                {
                    b.HasOne("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", "Device")
                        .WithMany("Rois")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("roi_device_id_fkey");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.Dashboard.CurDeviceEntity", b =>
                {
                    b.Navigation("Boxes");

                    b.Navigation("Frame");

                    b.Navigation("Roies");
                });

            modelBuilder.Entity("CSG.MI.TrMontrgSrv.EF.Entities.DeviceEntity", b =>
                {
                    b.Navigation("BoxCtrl");

                    b.Navigation("Boxes");

                    b.Navigation("Cfgs");

                    b.Navigation("DeviceCtrl");

                    b.Navigation("EvntLogs");

                    b.Navigation("FrameCtrl");

                    b.Navigation("Frames");

                    b.Navigation("Media");

                    b.Navigation("RoiCtrls");

                    b.Navigation("Rois");
                });
#pragma warning restore 612, 618
        }
    }
}
